version: '2'
services:
  # The Application
  laravel-api:
    build:
      context: ./_docker
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./${SPRINT_FOLDER}/API:/var/www:cached
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"

  angular-ui:
    build:
      context: ./_docker
      dockerfile: ui.docker
    working_dir: /app
    volumes:
      - ./${SPRINT_FOLDER}/UI:/app:cached
    ports:
      - 4200:4200
    command: >
      bash -c "npm install --force && ng serve --host 0.0.0.0 --port 4200"

  # The Web Server
  web:
    build:
      context: ./_docker
      dockerfile: web.docker
    working_dir: /var/www
    volumes:
      - laravel-api:/var/www
      - phpmyadmindata:/var/www/phpmyadmin
    ports:
      - 8091:80
      - 8000:81
    depends_on:
      - phpmyadmin
      - laravel-api

  cron:
    build:
      context: ./_docker/cron
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: cron
    restart: always
    command: crond -f -l 8
    volumes_from:
      - laravel-api
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"

  composer:
    image: composer:2.5.0
    command: install --no-dev --optimize-autoloader
    volumes_from:
      - laravel-api
    working_dir: /var/www

  # The Database
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    links:
      - mariadb:db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - phpmyadmindata:/var/www/html

  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1025:1025 # smtp server
      - 1080:1080 # web ui

volumes:
  db:
  phpmyadmindata:
  laravel-api:
