version: '3.8'
services:
  # The Application
  laravel-api:
    build:
      context: ./_docker
      dockerfile: api.docker
      target: development
    working_dir: /var/www
    volumes:
      - ./${SPRINT}/API:/var/www:cached
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"
      - DISABLE_LOGGING=${DISABLE_LOGGING}

  angular-ui:
    build:
      context: ./_docker
      dockerfile: ui.docker
      target: development
    working_dir: /app
    volumes:
      - ./${SPRINT}/UI:/app:cached
    ports:
      - 4200:4200
    command: >
      bash -c "npm install --force && ng serve --host 0.0.0.0 --port 4200"

  # The Web Server
  web:
    build:
      context: ./_docker
      dockerfile: web.docker
    working_dir: /var/www
    volumes:
      - laravel-api:/var/www
    ports:
      - 8091:80
      - 8000:81
    depends_on:
      - laravel-api

  composer:
    image: composer:2.6.6
    command: install --no-dev --optimize-autoloader --ignore-platform-req=ext-ffi && chown -R www-data /var/www && chmod 777 /var/www
    volumes_from:
      - laravel-api
    working_dir: /var/www

  # The Database
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

volumes:
  laravel-api:
